<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <title>Status Kehadiran Anda</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
    }
    .container {
      background-color: #ffffff;
      margin: 40px auto;
      padding: 20px;
      max-width: 600px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0,0,0,0.1);
    }
    .header {
      background-color: #2196F3;
      padding: 10px;
      color: white;
      text-align: center;
      border-radius: 8px 8px 0 0;
    }
    .content {
      padding: 20px;
      color: #333333;
    }
    .btn {
      display: inline-block;
      padding: 10px 20px;
      margin-top: 20px;
      background-color: #2196F3;
      color: white;
      text-decoration: none;
      border-radius: 5px;
    }
    .footer {
      font-size: 12px;
      color: #888888;
      text-align: center;
      padding: 10px;
      margin-top: 30px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h2>Konfirmasi Kehadiran Berhasil!</h2>
    </div>
    <div class="content">
      <p>Selamat, <strong><?= $username; ?></strong>! Anda telah berhasil melakukan konfirmasi kehadiran melalui <strong>Sistem Kehadiran!</strong></p>
      <p>Berikut adalah detail kehadiran tadi:</p>
      <ul>
        <li><strong>Nama Acara:</strong> <?= $event_name; ?></li>
        <li><strong>Tanggal & Waktu:</strong> <?= $waktu_konfirmasi; ?></li>
      </ul>
      <p>Terima kasih atas partisipasinya!</p>
    </div>
    <div class="footer">
      Email ini dikirim pada: <?= $tanggal_email; ?><br>
      Automatic Generated by FGroupIndonesia
    </div>
  </div>
</body>
</html>
