<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <title>Checkpoint Berhasil Dibuat!</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
    }
    .container {
      background-color: #ffffff;
      margin: 40px auto;
      padding: 20px;
      max-width: 600px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0,0,0,0.1);
    }
    .header {
      background-color: #4CAF50;
      padding: 10px;
      color: white;
      text-align: center;
      border-radius: 8px 8px 0 0;
    }
    .content {
      padding: 20px;
      color: #333333;
    }
    .btn {
      display: inline-block;
      padding: 10px 20px;
      margin-top: 20px;
      background-color: #4CAF50;
      color: white;
      text-decoration: none;
      border-radius: 5px;
    }
    .footer {
      font-size: 12px;
      color: #888888;
      text-align: center;
      padding: 10px;
      margin-top: 30px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h2>Checkpoint Anda Siap!</h2>
    </div>
    <div class="content">
      <p>Halo <strong><?= $username; ?></strong>,</p>
      <p>Selamat! Checkpoint Anda : <strong><?= $event_name; ?></strong> telah berhasil tergenerate dengan QR Code <strong><?= $jenis; ?></strong>.</p>
      <p>Silakan akses QR Code Anda melalui tautan berikut:</p>
      <p>
        <?php if($jenis == 'statis'): ?>
          <a href="<?= $link_qrcode; ?>" class="btn">Download Checkpoint</a>  
        <?php else : ?>
          <a href="<?= $link_qrcode; ?>" class="btn">Lihat Checkpoint</a>
        <?php endif; ?>
      </p>
      <p>Pastikan Anda menyimpan QR Code ini dengan baik untuk digunakan nantinya.</p>
    </div>
    <div class="footer">
      Email ini dikirim pada <?= $tanggal_email; ?><br>
      Automatic Generated by FGroupIndonesia 
    </div>
  </div>
</body>
</html>
