<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <title>Aktivasi Akun Sistem Absensi</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
    }
    .container {
      background-color: #ffffff;
      margin: 40px auto;
      padding: 20px;
      max-width: 600px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0,0,0,0.1);
    }
    .header {
      background-color: #4CAF50;
      padding: 15px;
      color: white;
      text-align: center;
      border-radius: 8px 8px 0 0;
    }
    .content {
      padding: 20px;
      color: #333333;
    }
    .btn {
      display: inline-block;
      padding: 10px 20px;
      margin-top: 20px;
      background-color: #4CAF50;
      color: white;
      text-decoration: none;
      border-radius: 5px;
    }
    .note {
      margin-top: 30px;
      font-size: 14px;
      color: #555555;
      background-color: #f9f9f9;
      padding: 10px;
      border-left: 4px solid #4CAF50;
    }
    .footer {
      font-size: 12px;
      color: #888888;
      text-align: center;
      padding: 10px;
      margin-top: 30px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h2>Aktivasi Akun Sistem Absensi</h2>
    </div>
    <div class="content">
      <p>Halo, <strong><?= $name; ?></strong>!</p>
      <p>Terima kasih telah mendaftar di <strong>Sistem Absensi</strong>. Untuk mulai menggunakan layanan ini, silakan aktivasi akun kamu melalui tombol di bawah ini:</p>

      <p style="text-align:center;">
        <a class="btn" href="<?= $link; ?>">Aktifkan Akun Saya</a>
      </p>

      <div class="note">
        <strong>Catatan:</strong> Pastikan kamu mengklik link aktivasi dari perangkat (ponsel) yang sama dengan yang akan kamu gunakan untuk absensi harian. Jika ada kendala, silakan hubungi admin melalui WhatsApp official FGroupIndonesia.
      </div>
    </div>
    <div class="footer">
      Email ini dibuat secara otomatis pada: <br>
      <?= $date; ?><br>
      <em>Automatic Generated by FGroupIndonesia</em>
    </div>
  </div>
</body>
</html>
