<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <title>Pemesanan Upgrade Akun Berhasil!</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
    }
    .container {
      background-color: #ffffff;
      margin: 40px auto;
      padding: 20px;
      max-width: 600px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0,0,0,0.1);
    }
    .header {
      background-color: #4CAF50;
      padding: 10px;
      color: white;
      text-align: center;
      border-radius: 8px 8px 0 0;
    }
    .content {
      padding: 20px;
      color: #333333;
    }
    .btn {
      display: inline-block;
      padding: 10px 20px;
      margin-top: 20px;
      background-color: #4CAF50;
      color: white;
      text-decoration: none;
      border-radius: 5px;
    }
    .payment-option {
      border: 1px solid #ddd;
      border-radius: 6px;
      padding: 10px;
      margin-bottom: 10px;
      display: flex;
      align-items: center;
      gap: 10px;
    }
    .payment-option img {
      width: 32px;
      height: 32px;
    }
    .footer {
      font-size: 12px;
      color: #888888;
      text-align: center;
      padding: 10px;
      margin-top: 30px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h2>Order Anda Telah Dibuat!</h2>
    </div>
    <div class="content">
      <p>Halo <strong><?= $username; ?></strong>,</p>
      <p>Order untuk Upgrade Akun : <strong><?= $jenis; ?></strong> dengan total <strong><?= format_rupiah($price); ?></strong> telah berhasil dibuat.</p>
      <p><strong>Harap lakukan pembayaran sebelum 3 jam dari sekarang</strong> agar order Anda tidak dibatalkan.</p>

      <h4>Metode Pembayaran:</h4>

      <div class="payment-option">
        <img src="<?=base_url('assets/img/bjb.png')?>" alt="Bank">
        <div>
          <strong>Bank Transfer</strong><br>
          Bank: BJB 005-869-395-210-0 <br>
          Holder Name: Astri Lutfiani Ulfah
        </div>
      </div>

      <div class="payment-option">
        <img src="<?=base_url('assets/img/gopay.png')?>" alt="GoPay">
        <div>
          <strong>GoPay</strong><br>
          Top up ke: <span class="fw-bold">0857-9556-9337</span>
        </div>
      </div>

      <div class="payment-option">
        <img src="<?=base_url('assets/img/shopee.png')?>" alt="ShopeePay">
        <div>
          <strong>ShopeePay</strong><br>
          Top up ke: <span class="fw-bold">0857-9556-9337</span>
        </div>
      </div>

      <p>Setelah melakukan pembayaran, silakan klik tombol di bawah untuk konfirmasi:</p>
      <a href="<?= $link_konfirmasi; ?>" class="btn">Konfirmasi Pembayaran</a>
    </div>
    <div class="footer">
      Email ini dikirim pada <?= $tanggal_email; ?><br>
      Automatic Generated by FGroupIndonesia
    </div>
  </div>
</body>
</html>
