<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <title>Pendaftaran Berhasil</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
    }
    .container {
      background-color: #ffffff;
      margin: 40px auto;
      padding: 20px;
      max-width: 600px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0,0,0,0.1);
    }
    .header {
      background-color: #2196F3;
      padding: 15px;
      color: white;
      text-align: center;
      border-radius: 8px 8px 0 0;
    }
    .content {
      padding: 20px;
      color: #333333;
    }
    .btn {
      display: inline-block;
      padding: 10px 20px;
      margin-top: 20px;
      background-color: #2196F3;
      color: white;
      text-decoration: none;
      border-radius: 5px;
    }
    .note {
      margin-top: 30px;
      font-size: 14px;
      color: #555555;
      background-color: #f9f9f9;
      padding: 10px;
      border-left: 4px solid #2196F3;
    }
    .footer {
      font-size: 12px;
      color: #888888;
      text-align: center;
      padding: 10px;
      margin-top: 30px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h2>Pendaftaran Berhasil</h2>
    </div>
    <div class="content">
      <p>Selamat datang, <strong><?= $username; ?></strong>!</p>
      <p>Akun kamu di <strong>Sistem Kehadiran</strong> telah berhasil dibuat.</p>
      <p>Jenis Akun yang kamu pilih : <strong><?= $jenis; ?></strong>.</p>
      <p>Silakan klik tombol berikut ini untuk login dan mulai menggunakan sistem:</p>

      <p style="text-align:center;">
        <a class="btn" href="<?= $link; ?>">Login ke dalam Portal Sistem</a>
      </p>

      <div class="note">
        <strong>Tips:</strong> Gunakan perangkat yang sama untuk login dan melakukan absensi harian. Jika lupa password atau mengalami kendala, hubungi admin melalui WhatsApp Official.
      </div>
    </div>
    <div class="footer">
      Email ini dibuat secara otomatis pada: <br>
      <?= $tanggal_email; ?><br>
      <em>Automatic Generated by FGroupIndonesia</em>
    </div>
  </div>
</body>
</html>
