<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <title>Pendaftaran Berhasil</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
    }
    .container {
      background-color: #ffffff;
      margin: 40px auto;
      padding: 20px;
      max-width: 600px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0,0,0,0.1);
    }
    .header {
      background-color: #2196F3;
      padding: 15px;
      color: white;
      text-align: center;
      border-radius: 8px 8px 0 0;
    }
    .content {
      padding: 20px;
      color: #333333;
    }
    .btn {
      display: inline-block;
      padding: 10px 20px;
      margin-top: 20px;
      background-color: #2196F3;
      color: white;
      text-decoration: none;
      border-radius: 5px;
    }
    .note {
      margin-top: 30px;
      font-size: 14px;
      color: #555555;
      background-color: #f9f9f9;
      padding: 10px;
      border-left: 4px solid #2196F3;
    }
    .footer {
      font-size: 12px;
      color: #888888;
      text-align: center;
      padding: 10px;
      margin-top: 30px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h2>Informasi Akun Baru</h2>
    </div>
    <div class="content">
      <p>Halo <strong><?= $username; ?></strong>,</p>
     <p>
          Akun kamu dengan email ini telah didaftarkan sebagai bagian dari : <br>
          <strong>unit 
            <?php 
              if (is_array($jenis_divisi)) {
                  echo implode(', ', $jenis_divisi);
              } else {
                  echo $jenis_divisi;
              }
            ?>
          </strong>
        </p>

      <p>Silakan akses instalasi <strong>Sistem Kehadiran</strong> melalui tautan di bawah ini:</p>

      <p style="text-align:center;">
        <a class="btn" href="<?= $link; ?>">Buka Sistem Kehadiran</a>
      </p>

      <div class="note">
        <strong>Penting:</strong> Gunakan perangkat (HP) utama kamu untuk mengaktifkan akun pertama kali. Setelah aktif, gunakan perangkat tersebut setiap hari untuk absensi harian.
      </div>
    </div>
    <div class="footer">
      Email ini dibuat secara otomatis pada:<br>
      <?= $tanggal_email; ?><br>
      <em>Automatic Generated by FGroupIndonesia</em>
    </div>
  </div>
</body>
</html>
