<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <title>Upgrade Membership Akun Berhasil</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
    }
    .container {
      background-color: #ffffff;
      margin: 40px auto;
      padding: 20px;
      max-width: 600px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0,0,0,0.1);
    }
    .header {
      background-color: #4CAF50;
      padding: 15px;
      color: white;
      text-align: center;
      border-radius: 8px 8px 0 0;
    }
    .content {
      padding: 20px;
      color: #333333;
      line-height: 1.6;
    }
    .btn {
      display: inline-block;
      padding: 10px 20px;
      margin-top: 20px;
      background-color: #4CAF50;
      color: white;
      text-decoration: none;
      border-radius: 5px;
    }
    .note {
      margin-top: 30px;
      font-size: 14px;
      color: #555555;
      background-color: #f9f9f9;
      padding: 10px;
      border-left: 4px solid #4CAF50;
    }
    .footer {
      font-size: 12px;
      color: #888888;
      text-align: center;
      padding: 10px;
      margin-top: 30px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h2>Selamat, Upgrade Berhasil!</h2>
    </div>
    <div class="content">
      <p>Hai <strong><?= $username; ?></strong>,</p>
      
      <p>
        Kabar baik buat kamu 🎉 tim sudah <strong>mengecek dan memverifikasi bukti pembayaranmu</strong>.  
        Mulai sekarang akunmu resmi naik level ke membership:
      </p>

      <p style="text-align:center; font-size:18px; font-weight:bold; color:#4CAF50;">
        <?= ucfirst($membership_name); ?>
      </p>

      <p>
        Terima kasih sudah mempercayakan layanan kami. Yuk, langsung login lagi ke aplikasi <strong>Sistem Kehadiran</strong> di perangkat utamamu dan nikmati semua fitur keren dari membership barumu.
      </p>

      <div class="note">
        <strong>Catatan:</strong> Demi kenyamanan, gunakan selalu perangkat utamamu untuk login.  
        Membership yang aktif ini hanya berlaku di akunmu saat ini.
      </div>
    </div>
    <div class="footer">
      Email ini dibuat otomatis pada:<br>
      <?= $tanggal_email; ?><br>
      <em>Automatic Generated by FGroupIndonesia</em>
    </div>
  </div>
</body>
</html>
